name: Sync, Minify and Push to Minified Branch

on:
  push:
    branches: ["main"]

jobs:
  sync-minify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '*'

    - name: Install Minification Tools
      run: |
        npm install -g html-minifier-terser clean-css-cli terser json-minify

    - name: Fetch all branches
      run: git fetch --all

    - name: Create or checkout the minified branch
      run: |
        git checkout -B minified origin/main

    - name: Minify HTML
      run: |
        find . -name '*.html' -exec html-minifier-terser --collapse-whitespace --remove-comments --minify-js true --minify-css true -o {} {} \; &
    
    - name: Minify CSS
      run: |
        find . -name '*.css' -exec cleancss -o {} {} \; &
    
    - name: Minify JS
      run: |
        find . -name '*.js' -exec terser --compress --mangle --output {} -- {} \; &
    
    - name: Minify JSON
      run: |
        find . -name '*.json' -exec sh -c 'json-minify < "$1" > "$1.tmp" && mv "$1.tmp" "$1"' _ {} \; &
    
    - name: Wait for all minification tasks to finish
      run: wait

    - name: Commit and Push Minified Files to Minified Branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add -u
        git commit -m "Minified HTML, CSS, JS, and JSON" || echo "Nothing to commit"
        git push --force "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" minified
